version: "3"
services:
 core:
   image: yuzutech/kroki
   environment:
     - KROKI_BLOCKDIAG_HOST=blockdiag
     - KROKI_MERMAID_HOST=mermaid
   ports:
     - "127.0.0.1:6180:8000"
 blockdiag:
   image: yuzutech/kroki-blockdiag
   ports:
     - "8001:8001"
 mermaid:
   image: yuzutech/kroki-mermaid
   ports:
     - "8002:8002"

